# Generated by Django 3.2.8 on 2021-11-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apt_name', models.CharField(max_length=100)),
                ('apt_location', models.TextField()),
                ('apt_area', models.IntegerField(blank=True, null=True)),
                ('apt_price', models.IntegerField(blank=True, null=True)),
                ('apt_beds', models.IntegerField(blank=True, null=True)),
                ('apt_baths', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('apt_lease', models.IntegerField(blank=True, null=True)),
                ('apt_deposit', models.IntegerField(blank=True, null=True)),
                ('apt_movein', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_reviewer', models.CharField(max_length=100)),
                ('apt_review', models.TextField()),
                ('apt_stars', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('apt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b02_housing_app.apartment')),
            ],
        ),
    ]
