# Generated by Django 3.2.8 on 2021-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_name', models.CharField(max_length=100)),
                ('apt_location', models.TextField()),
                ('apt_area', models.IntegerField()),
                ('apt_price', models.IntegerField()),
            ],
        ),
    ]
