# Generated by Django 3.2.8 on 2021-10-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apt_baths',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apt_beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apt_deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apt_lease',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apt_movein',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_price',
            field=models.IntegerField(null=True),
        ),
    ]
