# Generated by Django 3.2.8 on 2021-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
