# Generated by Django 3.2.8 on 2021-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0002_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='id',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
