# Generated by Django 3.2.8 on 2021-10-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0002_auto_20211026_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_reviewer', models.CharField(max_length=100)),
                ('apt_review', models.TextField()),
                ('apt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b02_housing_app.apartment')),
            ],
        ),
    ]
