# Generated by Django 3.2.8 on 2021-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0002_alter_apartment_apt_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_baths',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_lease',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_movein',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apt_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
