# Generated by Django 3.2.8 on 2021-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0004_review_apt_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='apt_stars',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
