# Generated by Django 3.2.8 on 2021-11-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b02_housing_app', '0006_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
